global:
  scrape_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  # Assuming you're using Alertmanager (optional)

rule_files:
  - "alert.rules.yml"  # Load alerting rules from an external file

scrape_configs:
  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'express-server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['express-server:3001']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Specify the module defined in blackbox.yml
    static_configs:
      - targets:
          - http://13.201.9.156  # Replace with your target URL
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Blackbox Exporter service address




